"""
Original Author: Rebecca Ringuette
Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bXjRv1Z3JDtA8cD4i_onsYycRwE5TId1
"""

from astropy.io import fits
print("astropy.io.fits imported successfully.")

import subprocess

# Import BeautifulSoup to parse the HTML and extract the FITS file links
try:
    from bs4 import BeautifulSoup
    print("BeautifulSoup module found!")
except ImportError:
#If BeautifulSoup not installed, install it
    print("BeautifulSoup not found. Installing...")
    #%pip install beautifulsoup4
    subprocess.run(["pip", "install beautifulsoup4"])
    from bs4 import BeautifulSoup
import json
import re

# Import requests library to fetch content of web directory
import requests
from urllib.parse import urljoin
import time
import os

def find_all_fits_urls(start_url, base_url_prefix, max_depth=4):
    # Initialize list of found urls for fits files
    fits_urls_found = []
    # Initialize set of urls already visited (set is unordered & unique)
    visited_urls = set()

    # Traverse file directory
    def _traverse(current_url, current_depth):
        if current_url in visited_urls or current_depth > max_depth:
            return
        visited_urls.add(current_url)

        print(f"Searching: {current_url} (Depth: {current_depth})")
        time.sleep(0.5) # Be polite to the server

        try:
            response = requests.get(current_url)
            # Raise HTTPError for bad responses (4xx or 5xx)
            response.raise_for_status()

            # Initialize HTML parser
            soup = BeautifulSoup(response.text, 'html.parser')

            # Extract links from hyperlink in HTML anchor (<a>) element
            for link in soup.find_all('a'):
                href = link.get('href')
                if href:
                    full_url = urljoin(current_url, href)

                    # Ensure traversal within specified base_url_prefix
                    if not full_url.startswith(base_url_prefix):
                        continue

                    if full_url.lower().endswith('.fits'):
                        fits_urls_found.append(full_url)
                    # Only traverse if full_url is a subdirectory of current_url
                    # and ensure it's a directory (ends with /) and not 
                    # the parent directory (..) or current directory (.)
                    elif full_url.endswith('/') and full_url != current_url\
                                                and full_url != urljoin(current_url, '../')\
                                                and full_url.startswith(current_url):
                        _traverse(full_url, current_depth + 1)

        except requests.exceptions.RequestException as e:
            print(f"Error fetching content from {current_url}: {e}")
        except Exception as e:
            print(f"An unexpected error occurred while processing {current_url}: {e}")

    _traverse(start_url, 0)
    return fits_urls_found

# Define base URL and prefix
base_url = "https://umbra.nascom.nasa.gov/punch/3/CAM/2026/02/20/"
#base_url = "https://umbra.nascom.nasa.gov/solar_orbiter/science/EUI/L2"
base_url_prefix = "https://umbra.nascom.nasa.gov/"

# Extract mission URL after base URL prefix
mission_url = base_url.split(base_url_prefix)[-1]

# Call function to find all FITS URLs
print("Starting FITS URL discovery...")
all_fits_file_urls = find_all_fits_urls(base_url, base_url_prefix, max_depth=4)

# Report number of FITS files found and print subset
print(f"\nFound {len(all_fits_file_urls)} FITS files")
for url in all_fits_file_urls[:10]:
    print(url)


# Now, define base URL of FITS file directory and a dictionary to store
# the results. Then, fetch HTML content of directory and parse it to
# find all links that point to `.fits` files. After that, for each FITS
# file found, open FITS file from URL using `astropy.io.fits` and 
# count the number of HDUs (headers) within it.

def extract_header(fits_url):

  # List to store all header dictionaries
  all_hdu_headers = []

  # Open the FITS file directly from the URL and process each HDU's header
  with fits.open(fits_url) as hdul:
      for i, hdu in enumerate(hdul):
          current_header_dict = {}
          for key, value in hdu.header.items():
              current_header_dict[key] = value
          all_hdu_headers.append(current_header_dict)
  print(f"Headers successfully extracted for {fits_url}\n")

  return all_hdu_headers

#extract_header("C:/Users/jwlilly/Downloads/PUNCH_L3_CAM_20260220001600_v0j.fits")
"""
def write_json(fits_url_to_convert, headers_list):

  # Convert the list of dictionaries to a JSON string
  json_output = json.dumps(headers_list, indent=2)

  # Define a local base directory for saving JSON files
  local_output_base_dir = "local_json_output" # This will create a directory in /content/

  # Ensure the local base output directory exists
  os.makedirs(local_output_base_dir, exist_ok=True)

  # Construct the filename using the previous flattening method
  base_url_prefix = "https://umbra.nascom.nasa.gov/"
  no_prefix_path = fits_url_to_convert.replace(base_url_prefix, "")
  flattened_path = no_prefix_path.replace("/", "_")

  # Replace .fits extension with .json
  json_filename = flattened_path.replace(".fits", ".json")

  # Construct the full local output path
  output_filename = os.path.join(local_output_base_dir, json_filename)

  # Write the JSON to a file
  with open(output_filename, 'w') as f:
      f.write(json_output)

  print(f"\nJSON output saved to: {output_filename}")

  return None

for file in all_fits_file_urls:
  headers_list = extract_header(file)
  write_json(file, headers_list)


# json_file_path = "local_json_output/punch_3_CAM_2026_02_20_PUNCH_L3_CAM_20260220084800_v0j.json"

# try:
#     with open(json_file_path, 'r') as f:
#         data = json.load(f)
#     print(json.dumps(data, indent=2))
# except FileNotFoundError:
#     print(f"Error: The file '{json_file_path}' was not found.")
# except json.JSONDecodeError:
#     print(f"Error: Could not decode JSON from '{json_file_path}'.")

# output_directory = "local_json_output"
# output_filename = "json_filenames.txt"

# # Get all files in the directory
# try:
#     filenames = os.listdir(output_directory)
#     # Filter out directories if any, though os.listdir returns names, not full paths
#     # For this specific task, we assume all entries are files based on previous steps.
#     files_only = [f for f in filenames if os.path.isfile(os.path.join(output_directory, f))]

#     # Write filenames to the text file, one per line
#     with open(output_filename, 'w') as f:
#         for filename in files_only:
#             f.write(filename + '\n')
#     print(f"All {len(files_only)} filenames from '{output_directory}' have been written to '{output_filename}'.")
# except FileNotFoundError:
#     print(f"Error: The directory '{output_directory}' was not found.")
# except Exception as e:
#     print(f"An error occurred: {e}")

# import zipfile

# output_directory = "local_json_output"
# zip_filename = "json_files_archive.zip"

# # Create a ZipFile object in write mode
# with zipfile.ZipFile(zip_filename, 'w') as zipf:
#     # Iterate over all files in the output directory
#     for root, _, files in os.walk(output_directory):
#         for file in files:
#             if file.endswith('.json'):
#                 file_path = os.path.join(root, file)
#                 # Add the file to the zip archive. The arcname ensures it's added
#                 # relative to the output_directory, not the full path.
#                 zipf.write(file_path, os.path.relpath(file_path, output_directory))

# print(f"Successfully created '{zip_filename}' containing all JSON files from '{output_directory}'.")

# import json
# from pprint import pprint

# files_in_folder = []
# for i, f in enumerate(os.listdir(output_directory)):
#     filename = os.path.join(output_directory, f)
#     files_in_folder.append(f)
#     name = f.split(".json")[0]
#     with open(filename, 'r') as fobj:
#         json_dict[f] = json.load(fobj)
# print(files_in_folder[:5])
# pprint(json_dict[f])

# os.listdir(output_directory)[:5],

# Need to know if the keys in each header of each files are the same across files.

# keyReflist0 = json_dict[files_in_folder[0]][0].keys()
# keyReflist1 = json_dict[files_in_folder[0]][1].keys()
# keyReflist2 = json_dict[files_in_folder[0]][2].keys()
# key_comparison0, key_comparison1, key_comparison2 = [], [], []
# for i in range(len(files_in_folder)):
#     keylist0 = json_dict[files_in_folder[i]][0].keys()
#     key_comparison0.append(keylist0 == keyReflist0)
#     if len(json_dict[files_in_folder[i]]) > 1:
#       keylist1 = json_dict[files_in_folder[i]][1].keys()
#       key_comparison1.append(keylist1 == keyReflist1)
#     else:
#       key_comparison1.append(False)
#     if len(json_dict[files_in_folder[i]]) > 2:
#       keylist2 = json_dict[files_in_folder[i]][2].keys()
#       key_comparison2.append(keylist2 == keyReflist2)
#     else:
#       key_comparison2.append(False)
# print(len(files_in_folder), sum(key_comparison0), sum(key_comparison1), sum(key_comparison2))

# Since they are different, need the full set of possible header fields across the entire set of files."""

# import numpy as np

# key_list0, key_list1, key_list2 = [], [], []
# for i in range(len(files_in_folder)):
#     if len(json_dict[files_in_folder[i]]) > 2:
#         key_list0.extend(json_dict[files_in_folder[i]][0].keys())
#         key_list1.extend(json_dict[files_in_folder[i]][1].keys())
#         key_list2.extend(json_dict[files_in_folder[i]][2].keys())
#         print(i, len(json_dict[files_in_folder[i]][0].keys()), len(json_dict[files_in_folder[i]][1].keys()), len(json_dict[files_in_folder[i]][2].keys()))
#     elif len(json_dict[files_in_folder[i]]) > 1:
#         key_list0.extend(json_dict[files_in_folder[i]][0].keys()) # it looks like some of the hdu0 headers are missing for solar orbiter
#         key_list1.extend(json_dict[files_in_folder[i]][0].keys())
#         print(i, len(json_dict[files_in_folder[i]][0].keys()), len(json_dict[files_in_folder[i]][1].keys()))
#     else:
#         key_list0.extend(json_dict[files_in_folder[i]][0].keys())
#         print(i, len(json_dict[files_in_folder[i]][0].keys()))
# key_list0 = np.unique(np.array(key_list0))
# key_list1 = np.unique(np.array(key_list1))
# key_list2 = np.unique(np.array(key_list2))
# print(len(key_list0), len(key_list1), len(key_list2))
# With the full list of possible headers now determined, iterate through the json files and extract the header information. If the header doesn't exist in the file, then enter "None". As a sanity check, make sure the number of entries per header is the same as the number of files.

# header0, header1, header2 = {}, {}, {}

# for i in range(len(files_in_folder)):
#     if len(json_dict[files_in_folder[i]]) > 2:
#         for key in key_list2:
#             if key not in header2.keys():
#                 header2[str(key)] = []
#             if key in json_dict[files_in_folder[i]][2].keys():
#                 header2[str(key)].append(json_dict[files_in_folder[i]][2][key])
#             else:
#                 header2[str(key)].append(None)
#         for key in key_list1:
#             if key not in header1.keys():
#                 header1[str(key)] = []
#             if key in json_dict[files_in_folder[i]][1].keys():
#                 header1[str(key)].append(json_dict[files_in_folder[i]][1][key])
#             else:
#                 header1[str(key)].append(None)
#         for key in key_list0:
#             if key not in header0.keys():
#                 header0[str(key)] = []
#             if key in json_dict[files_in_folder[i]][0].keys():
#                 header0[str(key)].append(json_dict[files_in_folder[i]][0][key])
#             else:
#                 header0[str(key)].append(None)
#     elif len(json_dict[files_in_folder[i]]) > 1:
#         for key in key_list1:
#             if key not in header1.keys():
#                 header1[str(key)] = []
#             if key in json_dict[files_in_folder[i]][1].keys():
#                 header1[str(key)].append(json_dict[files_in_folder[i]][1][key])
#             else:
#                 header1[str(key)].append(None)
#         for key in key_list0:
#             if key not in header0.keys():
#                 header0[str(key)] = []
#             if key in json_dict[files_in_folder[i]][0].keys():
#                 header0[str(key)].append(json_dict[files_in_folder[i]][0][key])
#             else:
#                 header0[str(key)].append(None)
#     else:
#         for key in key_list1:
#             if key not in header1.keys():
#                 header1[str(key)] = []
#             if key in json_dict[files_in_folder[i]][0].keys():
#                 header1[str(key)].append(json_dict[files_in_folder[i]][0][key])
#             else:
#                 header1[str(key)].append(None)
#         for key in key_list0:  # hdu0 is missing
#             if key not in header0.keys():
#                 header0[str(key)] = []
#             header0[str(key)].append(None)

# for key in header0.keys():
#     print(key, len(header0[key]), len(header0[key]) == len(files_in_folder))
# for key in header1.keys():
#     print(key, len(header1[key]), len(header1[key]) == len(files_in_folder))
# for key in header2.keys():
#     print(key, len(header2[key]), len(header2[key]) == len(files_in_folder))
# print("header extraction complete")

# Figure out how many entries for a given metadata field are not None.

# print("In HDU0: header name, count, first value")
# for key in header0.keys():
#     count = len([x for x in header0[key] if x is not None])
#     print(key, count, header0[key][0])
# print("\nIn HDU1: header name, count, first value")
# for key in header1.keys():
#     count = len([x for x in header1[key] if x is not None])
#     print(key, count, header1[key][0])
# print("\nIn HDU2: header name, count, first value")
# for key in header2.keys():
#     count = len([x for x in header2[key] if x is not None])
#     print(key, count, header2[key][0])

# Need to find the files with the most metadata fields

# print("\nFile comparison")
# count_list = []
# for i in range(len(files_in_folder)):
#     value_list = [value[i] for key, value in header0.items()]
#     value_list.extend([value[i] for key, value in header1.items()])
#     value_list.extend([value[i] for key, value in header2.items()])
#     count_list.append(len([x for x in value_list if x is not None]))
#     # print(files_in_folder[i], len(value_list), count_list[-1])

# unique_count = np.unique(np.array(count_list))
# max_index = count_list.index(max(count_list))
# print("Total possible number of headers per file:",len(header0.keys()) + len(header1.keys()) + len(header2.keys()))
# print("Number of headers per file:", unique_count)
# print("File with max number of headers:", files_in_folder[max_index])
# print("Number of headers for that file:", max(count_list))
# print("Missing header(s) for that file:", [key for key, value in header0.items() if header0[key][max_index] is None], [key for key, value in header1.items() if header1[key][max_index] is None], [key for key, value in header2.items() if header2[key][max_index] is None])

# print(header0.keys())
# print(header1.keys())
# print(header2.keys())

# import json

# # Define the output file paths
# header0_json_path = "header0.json"
# header1_json_path = "header1.json"
# header2_json_path = "header2.json"

# # Save header0 to a JSON file
# with open(header0_json_path, 'w') as f:
#     json.dump(header0, f, indent=2)
# print(f"header0 saved to {header0_json_path}")

# # Save header1 to a JSON file
# with open(header1_json_path, 'w') as f:
#     json.dump(header1, f, indent=2)
# print(f"header1 saved to {header1_json_path}")

# # Save header2 to a JSON file
# with open(header2_json_path, 'w') as f:
#     json.dump(header2, f, indent=2)
# print(f"header2 saved to {header2_json_path}")

# unique_header0, unique_header1, unique_header2 = {}, {}, {}
# for key in header0.keys():
#     unique_header0[key] = str(np.unique(np.array([x for x in header0[key] if x is not None])))
# for key in header1.keys():
#     unique_header1[key] = str(np.unique(np.array([x for x in header1[key] if x is not None])))
# for key in header2.keys():
#     unique_header2[key] = str(np.unique(np.array([x for x in header2[key] if x is not None])))

# import json

# # Define the output file paths
# unique_header0_json_path = "unique_header0.json"
# unique_header1_json_path = "unique_header1.json"
# unique_header2_json_path = "unique_header2.json"

# # Save header0 to a JSON file
# with open(unique_header0_json_path, 'w') as f:
#     json.dump(unique_header0, f, indent=2)
# print(f"header0 saved to {unique_header0_json_path}")

# # Save header1 to a JSON file
# with open(unique_header1_json_path, 'w') as f:
#     json.dump(unique_header1, f, indent=2)
# print(f"header1 saved to {unique_header1_json_path}")

# # Save header2 to a JSON file
# with open(unique_header2_json_path, 'w') as f:
#     json.dump(unique_header2, f, indent=2)
# print(f"header2 saved to {unique_header2_json_path}")

# header_list = list(header0.keys())
# header_list.extend(list(header1.keys()))
# header_list.extend(list(header2.keys()))
# print(len(header_list), header_list)
# unique_headers = np.unique(np.array(header_list))
# print(len(unique_headers), unique_headers)

# import pandas as pd

# # Create a DataFrame from the header_list
# df_headers = pd.DataFrame(header_list, columns=['Header_Keys'])

# # Save the DataFrame to a CSV file
# csv_filename = 'fits_headers.csv'
# df_headers.to_csv(csv_filename, index=False)

# print(f"Header keys saved to {csv_filename}")